In [9]:
# 1. Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean,
# and standard deviation of the array.
import numpy as np
a=np.random.randint(0,11,size=(3,3))
print(a)
print(a.sum())
print(a.mean())
print(a.std())

[[ 9 10  6]
 [10  5  5]
 [ 1  0  3]]
49
5.444444444444445
3.4995590551163605


In [16]:
# 2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.
a=np.arange(1,11)
print(a)
print(np.cumsum(a))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  6 10 15 21 28 36 45 55]


In [24]:
# 3. Generate two 2x3 arrays with random integers and perform element-wise addition,
#    subtraction, multiplication, and division.
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(1,10,size=(2,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.round(a/b,2))

[[4 9 4]
 [1 3 3]]
[[2 7 6]
 [7 1 2]]
[[ 6 16 10]
 [ 8  4  5]]
[[ 2  2 -2]
 [-6  2  1]]
[[ 8 63 24]
 [ 7  3  6]]
[[2.         1.28571429 0.66666667]
 [0.14285714 3.         1.5       ]]
[[2.   1.29 0.67]
 [0.14 3.   1.5 ]]


In [27]:
# 4. Create a 4x4 identity matrix.
a=np.eye(4,4)
print(a)

identity=np.eye(4,dtype=int)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
# 5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.a=np.random.randint(1,10,size=(2,3))
a=np.array([5,20,25,20,25])
print(a)
print(a/5)
#how division answer came?

[ 5 20 25 20 25]
[1. 4. 5. 4. 5.]


In [57]:
6. Reshape a 1D array of 12 elements into a 3x4 matrix.
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=a.reshape(3,4)
print(b)
# I manually define(custom data) the elements.can define elements in lists, tuples, etc
# Good when I already have specific values.Flexibility = any values our wish

b=np.arange(1,13)
print(b)
c=b.reshape(3,4)
print(c)
# Automatically generates(Sequential data) numbers from 1 to 12.Automatically creates numbers in a range
# Syntax: arange(start, stop, step)
# Cleaner and faster for sequences, Flexibility = Limited to numeric pattern

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
#7. Flatten a 3x3 matrix into a 1D array.
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

b=np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
#8. Stack two 3x3 matrices horizontally and vertically.
a=np.ones((3,3),dtype=int)
b=np.ones((3,3),dtype=int)
print(a)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [87]:
#9. Concatenate two arrays of different sizes along a new axis.
a= np.array([1, 2, 3])
b= np.array([4, 5, 6, 7])
# Pad to equal length, then stack along new axis
max_len = max(len(a), len(b))
a_padded = np.pad(a, (0, max_len - len(a)), constant_values=0)
b_padded = np.pad(b, (0, max_len - len(b)), constant_values=0)
result = np.stack([a_padded, b_padded], axis=0)
print("A (padded):", a_padded)
print("B (padded):", b_padded)
print("Stacked along new axis (axis=0):\n", result)

A (padded): [1 2 3 0]
B (padded): [4 5 6 7]
Stacked along new axis (axis=0):
 [[1 2 3 0]
 [4 5 6 7]]


In [88]:
#10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 column import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
transposed = a.T
print(transposed)
reshaped10 = transposed.reshape(3, 2)
print(reshaped10)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3]
 [5 2]
 [4 6]]


In [89]:
#11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.
a = np.arange(1, 16)
print("Array:    ", a)
print("Extracted:", a[2:10:2])


Array:     [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Extracted: [3 5 7 9]


In [10]:
#12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
print("5x5 Matrix:\n", arr)
print("Sub-matrix (rows 1:4, cols 2:5):\n", arr[1:4, 2:5])

5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sub-matrix (rows 1:4, cols 2:5):
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [7]:
#13. Replace all elements in a 1D array greater than 10 with the value 10.
arr = np.array([3, 15, 7, 22, 9, 11, 4, 18])
print("Original:  ", arr)
arr[arr > 10] = 10
print("After clip:", arr)

Original:   [ 3 15  7 22  9 11  4 18]
After clip: [ 3 10  7 10  9 10  4 10]


In [8]:
#14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:            ", arr)
print("Fancy indexed:    ", arr[[0, 2, 4, 6]])


Array:             [10 20 30 40 50 60 70 80]
Fancy indexed:     [10 30 50 70]


In [9]:
#15. Create a 1D array of 10 elements and reverse it using slicing
arr = np.arange(1, 11)
print("Original: ", arr)
print("Reversed: ", arr[::-1])

Original:  [ 1  2  3  4  5  6  7  8  9 10]
Reversed:  [10  9  8  7  6  5  4  3  2  1]


In [12]:
#16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.
mat16 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row16 = np.array([10, 20, 30])
print("Matrix:\n", mat16)
print("Row array:", row16)
print("Result:\n", mat16 + row16)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row array: [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [13]:
#17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.
arr17 = np.array([1, 2, 3, 4, 5])
scalar = 7
print("Array: ", arr17)
print(f"x {scalar} =", arr17 * scalar)


Array:  [1 2 3 4 5]
x 7 = [ 7 14 21 28 35]


In [14]:
#18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.
mat18 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
col18 = np.array([[1], [2], [3]])
print("Matrix:\n", mat18)
print("Column vector:\n", col18)
print("Result:\n", mat18 - col18)


Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Column vector:
 [[1]
 [2]
 [3]]
Result:
 [[ 9 19 29]
 [38 48 58]
 [67 77 87]]


In [16]:
#19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
arr19 = np.ones((2, 3, 4), dtype=int)
scalar19 = 5
result19 = arr19 + scalar19
print("3D array shape:", arr19.shape)
print(f"Scalar: {scalar19}")
print("Result shape:  ", result19.shape)
print("First slice:\n", result19[0])
    


3D array shape: (2, 3, 4)
Scalar: 5
Result shape:   (2, 3, 4)
First slice:
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [18]:
#20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.
a20 = np.array([[1], [2], [3], [4]])          # shape (4,1)
b20 = np.array([[10, 20, 30, 40, 50]])         # shape (1,5)
result20 = a20 + b20
print("A (4,1):\n", a20)
print("B (1,5):\n", b20)
print("Result (4,5):\n", result20)



A (4,1):
 [[1]
 [2]
 [3]
 [4]]
B (1,5):
 [[10 20 30 40 50]]
Result (4,5):
 [[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]


In [3]:
#21. Compute the square root of each element in a 2D array using vectorized operations.
import numpy as np
arr = np.array([[4, 16, 25],
                [9, 36, 49]])

# Compute square root of each element
sqrt_arr = np.sqrt(arr)  # np.sqrt applies square root to each element automatically

print("Original array:\n", arr)
print("Square root of each element:\n", sqrt_arr)

Original array:
 [[ 4 16 25]
 [ 9 36 49]]
Square root of each element:
 [[2. 4. 5.]
 [3. 6. 7.]]


In [ ]:
# 22. Calculate the dot product of two 1D arrays of size 5.
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Calculate dot product
dot_product = np.dot(a, b)  # np.dot computes sum(a[i]*b[i])

# Display results
print("Array a:", a)
print("Array b:", b)
print("Dot product:", dot_product)

In [4]:
# 23. Perform element-wise comparison of two 1D arrays and return an array of boolean values
# indicating where the first array has larger elements.

x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 15, 35, 30, 50])

# Compare elements of x with y
comparison = x > y  # Returns a boolean array: True if x[i] > y[i]

print("x:", x)
print("y:", y)
print("x > y:", comparison)

x: [10 20 30 40 50]
y: [15 15 35 30 50]
x > y: [False  True False  True False]


In [5]:
# 24. Create a 2D array and apply a vectorized operation to double the value of each element.
arr2d = np.array([[1, 2], [3, 4]])
doubled = arr2d * 2  # Multiplication is applied element-wise

print("Original 2D array:\n", arr2d)
print("Doubled array:\n", doubled)

Original 2D array:
 [[1 2]
 [3 4]]
Doubled array:
 [[2 4]
 [6 8]]


In [6]:
# 25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.
rand_arr = np.random.randint(1, 101, size=100)

# Select even numbers using modulo operation
even_numbers = rand_arr[rand_arr % 2 == 0]

# Compute sum of even numbers
sum_even = np.sum(even_numbers)
print("Random array:\n", rand_arr)
print("Even numbers:\n", even_numbers)
print("Sum of even numbers:", sum_even)

Random array:
 [37 28 22 56  8 73 40 49 82 56 95 27 14  4 59 65 62 62 33  6  8 87  3 98
 99 56 48 83  3 43 83 11 50 28 86  3 99 33 23 31 36 68 71 62 63 62 78 43
 28  7 25  2  5 46 36 32 82 91 79 93 91 84 76 61 28 75 81 63 28 37 96 28
 24 89 94 97 98  7 29 12 53 72 95 66 86 29 78 16 57 48 40 65 51  6 10 31
 80 23 65 35]
Even numbers:
 [28 22 56  8 40 82 56 14  4 62 62  6  8 98 56 48 50 28 86 36 68 62 62 78
 28  2 46 36 32 82 84 76 28 28 96 28 24 94 98 12 72 66 86 78 16 48 40  6
 10 80]
Sum of even numbers: 2416


In [7]:
# 26. Create a 3x3 matrix and find its determinant.
mat3x3 = np.array([[1, 2, 3],
                   [0, 4, 5],
                   [1, 0, 6]])
determinant = np.linalg.det(mat3x3)
print("3x3 matrix:\n", mat3x3)
print("Determinant:", determinant)

3x3 matrix:
 [[1 2 3]
 [0 4 5]
 [1 0 6]]
Determinant: 22.000000000000004


In [8]:
# 27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.
mat2x2 = np.array([[4, 7],
                   [2, 6]])
# Compute inverse
inv_mat = np.linalg.inv(mat2x2)

# Multiply original and inverse to verify identity
identity = np.dot(mat2x2, inv_mat)

print("Original matrix:\n", mat2x2)
print("Inverse matrix:\n", inv_mat)
print("Product (should be identity matrix):\n", identity)

Original matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Product (should be identity matrix):
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [9]:
# 28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.
matrix = np.array([[2, 1],
                   [1, 2]])
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Matrix:
 [[2 1]
 [1 2]]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
# 29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.
# Coefficient matrix
A = np.array([[2, 3],
              [4, 6]])

# Right-hand side
b = np.array([5, 10])

# Try solving the system
try:
    solution = np.linalg.solve(A, b)
    print("Solution:", solution)
except np.linalg.LinAlgError:
    print("No unique solution (matrix is singular).")


No unique solution (matrix is singular).


In [11]:
# 30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original
# matrix using the SVD components.

matrix_svd = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
# Perform SVD
U, S, Vt = np.linalg.svd(matrix_svd)

# S is returned as 1D array of singular values, convert to diagonal matrix
S_matrix = np.zeros((3, 3))
np.fill_diagonal(S_matrix, S)

# Reconstruct original matrix
reconstructed = np.dot(U, np.dot(S_matrix, Vt))

print("Original matrix:\n", matrix_svd)
print("U matrix:\n", U)
print("Singular values (S):\n", S_matrix)
print("Vt matrix:\n", Vt)
print("Reconstructed matrix:\n", reconstructed)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
U matrix:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values (S):
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]
Vt matrix:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Reconstructed matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
