In [3]:
# 1. Create a NumPy array of random numbers and normalize the data using min-max scaling.
#Create a NumPy array with 10 random numbers between 0 and 1
import numpy as np
random_array = np.random.rand(10)
print("Original array:", random_array)

# Min-Max Normalization formula: (x - min) / (max - min)
min_val = random_array.min()  # Find minimum value in the array
max_val = random_array.max()  # Find maximum value in the array

normalized_array = (random_array - min_val) / (max_val - min_val)
print("Normalized array:", normalized_array)                                                               

Original array: [0.87306418 0.70454291 0.22054691 0.64188948 0.71084159 0.04052585
 0.33474254 0.60388111 0.00545081 0.80119832]
Normalized array: [1.         0.80576456 0.247917   0.73355102 0.81302433 0.04042705
 0.37953742 0.68974307 0.         0.91716834]


In [4]:
# 2. Generate a 5x5 matrix with random integers and replace all occurrences of a specific value with another.
# Create a 5x5 matrix with random integers from 1 to 10
matrix = np.random.randint(1, 11, size=(5,5))
print("Original matrix:\n", matrix)

# Replace all occurrences of the value 5 with 99
matrix[matrix == 5] = 99
print("Modified matrix:\n", matrix)

Original matrix:
 [[ 6  4  5  7  3]
 [ 4  3  2  6  6]
 [ 2  3  2  3  1]
 [ 8  3 10  7  1]
 [ 2  7  4  5  3]]
Modified matrix:
 [[ 6  4 99  7  3]
 [ 4  3  2  6  6]
 [ 2  3  2  3  1]
 [ 8  3 10  7  1]
 [ 2  7  4 99  3]]


In [5]:
# 3. Create two NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# Create two NumPy arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise operations
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [6]:
# 4. Solve the system of linear equations: \(3x + 4y = 7\) and \(5x + 2y = 8\) using NumPy.
# Coefficient matrix
A = np.array([[3, 4],
              [5, 2]])

# Right-hand side
B = np.array([7, 8])

# Solve the system
solution = np.linalg.solve(A, B)
print("Solution [x, y]:", solution)

Solution [x, y]: [1.28571429 0.78571429]


In [7]:
# 5. Implement broadcasting to perform an operation between a 3x3 matrix and a 1D array.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# 1D array
arr = np.array([1, 0, -1])

# Broadcasting: add 1D array to each row of matrix
result = matrix + arr
print("Result after broadcasting:\n", result)


Result after broadcasting:
 [[2 2 2]
 [5 5 5]
 [8 8 8]]


In [8]:
# 6. Create a 3x3 identity matrix using NumPy
identity_matrix = np.eye(3)
print("3x3 Identity matrix:\n", identity_matrix)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 7. Perform matrix multiplication between two 2D arrays.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication result:\n", C)


Matrix multiplication result:
 [[19 22]
 [43 50]]


In [10]:
# 8. Calculate the dot product and cross product of two vectors using NumPy.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Dot product
dot_product = np.dot(v1, v2)
print("Dot product:", dot_product)

# Cross product
cross_product = np.cross(v1, v2)
print("Cross product:", cross_product)

Dot product: 32
Cross product: [-3  6 -3]


In [11]:
# 9. Generate a NumPy array of 20 random integers and find the unique elements in the array.
arr = np.random.randint(1, 11, 20)
print("Random array:", arr)

# Find unique elements
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

Random array: [8 4 7 4 6 3 7 5 6 7 1 9 7 6 8 3 9 9 5 1]
Unique elements: [1 3 4 5 6 7 8 9]


In [12]:
# 10. Implement a function using NumPy that returns the inverse of a given matrix.
def inverse_matrix(matrix):
    """
    Returns the inverse of a square matrix.
    """
    try:
        inv = np.linalg.inv(matrix)
        return inv
    except np.linalg.LinAlgError:
        return "Matrix is singular and cannot be inverted"

# Example 2x2 matrix
matrix = np.array([[1, 2],
                   [3, 4]])

inverse = inverse_matrix(matrix)
print("Inverse of the matrix:\n", inverse)

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
